// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           13
// Async Callback (empty):               1
// Total number of exported functions:  16

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    crowdfunding_plus
    (
        init => init
        upgrade => upgrade
        fund => fund
        claim => claim
        setMaxDepositPerDonor => set_max_deposit_per_donor
        setMaxTarget => set_max_target
        setMinFund => set_min_fund
        status => status
        getCurrentFunds => get_current_funds
        getTarget => target
        getDeadline => deadline
        getDeposit => deposit
        getMinFund => min_fund
        getMaxDepositPerDonor => max_deposit_per_donor
        getMaxTarget => max_target
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
